### PR TITLE
Add ability to change icon classes

### PR DESCRIPTION
**Pull request by khornberg**
I could not install the `bootstrap-datetimepicker` from npm. I saw your comment on an issue there. That commit could be popped off but I don't know how I could install this then.

### CODE REVIEW

**Comment by btecu** [comment]
Adding the ability to change the icon is great. It increases the api but it's useful.
Could you name it `iconClass` instead of `classes`?
I'm not sure `iconText` is useful. Do you have a use case for it?

What issues are you running into with `npm`? It should be a different pull request, although, downgrading is not an option as the older version has some issues with null/undefined dates.

Once you make the changes I should be able to merge.

**Comment by khornberg** [comment]
Yes I can rename the class. Should the class variable be plural or not since one could have several classes to be applied?
`iconText` is for [material design icons](http://google.github.io/material-design-icons/).

I was unable to install `bootstrap-datetimepicker` because the version was unavailable on `npm`. I'll try it again tomorrow.

**Comment by btecu** [comment]
I was unaware of material design icons working that way.
Yes, `iconClasses` and `iconText` seems good.

Here is the npm package:
https://www.npmjs.com/package/eonasdan-bootstrap-datetimepicker-npm

**Comment by khornberg** [comment]
Ok. The naming has been changed in this PR and the dependency commit removed.

I see what you did now with the dependency. I think my probably was that I was trying to do an `npm install` from the `package.json` in this repo to run the tests rather than installing it into an ember app. The `package.json` of this repo does not have `eonasdan-bootstrap-datetimepicker-npm` as a dependency. Should it?

**Comment by btecu** [comment]
Yes, it should. I'll fix that and bump the version.

**Comment by btecu** [comment]
Version `0.1.4` released. Thanks.

**Pull request merged**
