### PR TITLE
Downgrade node to v4 for ember-cli compat

### PR DESCRIPTION
**Pull request by ultimatemonty**
Addresses #39 

/cc @btecu

### CODE REVIEW

**Comment by btecu** [comment]
Have you tested this locally with node 4? I thought it was something in `index.js` that was not supported.

**Comment by ultimatemonty** [comment]
I see what you were saying about node v4 - 4.8.0 LTS blows up hard on any generator command. 4.5 works just fine.

Was digging through the ember-cli repo and the latest package.json (for `2.12.0-beta.2`) has the [node version](https://github.com/ember-cli/ember-cli/blob/master/package.json#L148) set to `^4.5 || 6.* || 7.*`

If I'm reading that glob correctly it's saying v4.5.x, 6.x, and 7.x are all supported. Seems smart to do the same here. Thoughts?

**Comment by btecu** [comment]
That might be confusing for users, but it should work.

**Comment by ultimatemonty** [comment]
@btecu I'm gonna kill this PR while I fall into the rabbit hole that is node debugging. Genuinely curious what's blowing up the generator. Will open a new one when I emerge!

**Pull request closed without merging**
