### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by m-adler**
Not sure you're interested in reactivating the commented-out tests.
I think it's better to have some simple tests than none.
I marked a failing test as todo instead of deleting it because I don't know how far it reflects the desired behavior. This way, the issue with this test can be addressed later without losing track of it.

### CODE REVIEW

**Comment by btecu** [comment]
I agree, it would be good to have some tests. Is that something you'd be interested in working on?

**Comment by m-adler** [comment]
Just added somt tests. I also removed the test that was marked as todo, because it turned out that this test was testing unintended behaviour.
The ESLint ember/no-attrs-in-components error is now also ignored. I created the issue #64 to keep track on this.

**Comment by m-adler** [comment]
By the way ...
The dedicated ESLint check (`eslint .`) could be removed in the test.
https://travis-ci.org/btecu/ember-cli-bootstrap-datetimepicker/jobs/471230102#L531
This one seems to use slightly different rules for validation than ember, so there is still one error.
However, I think that you can still remove it, since `ember test` also validates it.

**Comment by btecu** [comment]
Wouldn't an updated blueprint take care of that check if that was the case?

**Comment by m-adler** [comment]
I have to admit that I have no idea by whom or what the test at https://travis-ci.org/btecu/ember-cli-bootstrap-datetimepicker/jobs/471230102 was created.

If it is completely generated from the .travis.yml, there is nothing to change according to `ember init`.
But there are suggested changes für `tests/dummy/config/environment.js`.

```
? Overwrite tests/dummy/config/environment.js? Diff
Index: /home/m-adler/ember-cli-bootstrap-datetimepicker/tests/dummy/config/environment.js
===================================================================
--- /home/m-adler/ember-cli-bootstrap-datetimepicker/tests/dummy/config/environment.js
+++ /home/m-adler/ember-cli-bootstrap-datetimepicker/tests/dummy/config/environment.js
@@ -6,12 +6,15 @@
     environment,
     rootURL: '/',
     locationType: 'auto',
     EmberENV: {
-      EXTEND_PROTOTYPES: false,
       FEATURES: {
         // Here you can enable experimental features on an ember canary build
         // e.g. 'with-controller': true
+      },
+      EXTEND_PROTOTYPES: {
+        // Prevent Ember Data from overriding Date.parse.
+        Date: false
       }
     },

     APP: {
@@ -40,9 +43,9 @@
     ENV.APP.autoboot = false;
   }

   if (environment === 'production') {
-
+    // here you can enable a production-specific feature
   }

   return ENV;
 };
```

Adding the comment should also satisfy the last failed test.

**Comment by btecu** [comment]
Yes, either adding the comment or removing the if block seems fine.

**Comment by m-adler** [comment]
Done

**Comment by btecu** [comment]
Thanks!

**Pull request merged**
